### ISSUE TITLE
Can't  train with VOC2007 get error

### ISSUE THREAD

**Issue by xor0x** [tanakataiki/ssd_kerasV2#25]
Please help cant train get error 
ValueError: shape mismatch: value array of shape (12,20) could not be broadcast to indexing result of shape (12,3)

**Comment by tomsblueskeye** [comment]
How did you solve this problem?

**Comment by pedromlsreis** [comment]
@xor0x Can you please share how you solved this issue?

**Comment by Ayumu-J-S** [comment]
I had a similar error. For me, the problem was that some of the input images were in grayscale, so when cv2 reads the image, the dimension was coming in as 2. So I just added 
`if len(img.shape) == 2: img = cv2.cvtColor(img,cv2.COLOR_GRAY2BGR)`

right after `mg = imread(img_path).astype('float32')` in *generate()*.
